language: python
install:
  - pip install -r setup/requirements.txt
  - pip install -r setup/requirements.dev.txt
python:
  - "2.7"
script:
  - nosetests tests/unit/test.py --with-coverage --cover-package=cahoots --cover-min-percentage 71
  - flake8 cahoots tests web